server:
  port: 8088
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MEHIKE/config-repo.git
          skipSslValidation: true
          
          
#spring.cloud.config.server.git.uri: file://${user.home}/config-repo
          
          